EICO/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^inicio/', include('home.urls', namespace="home")),
    url(r'^foro/', include('forum.urls', namespace="forum")),
    url(r'^calendario/', include('eicocalendar.urls', namespace="calendario")),
    url(r'^perfil/', include('personal.urls', namespace="perfil")),
]

home/urls.py
from django.conf.urls import url, include
from . import views

app_name = "home"



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^solicitarUsuario/$', views.solicitarUsuario, name='solicitarUsuario'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^errorLogin/$', views.errorLogin, name='errorLogin'),
    url(r'^servicio$', views.viewService, name='viewService'),
    url(r'^interes$', views.viewInteres, name='viewInteres'),
    url(r'^admin$', views.admin, name='admin'),
    url(r'^admin/estadisticasVisitas/$', views.estadisticasVisitas, name='estadisticasVisitas'),
    url(r'^admin/estadisticasVisitasAux/$', views.estadisticasVisitasAux, name='estadisticasVisitasAux'),
    url(r'^admin/estadisticasReacciones/$', views.estadisticasReacciones, name='estadisticasReacciones'),
    url(r'^admin/estadisticasReaccionesAux/$', views.estadisticasReaccionesAux, name='estadisticasReaccionesAux'),
    url(r'^admin/agregarSitio$', views.agregarSitio, name='agregarSitio'),
    url(r'^admin/agregarServicio$', views.agregarServicio, name='agregarServicio'),
    url(r'^admin/agregarUsuarios$', views.agregarUsuarios, name='agregarUsuarios'),
    url(r'^admin/editar/(?P<id>[0-9]+)$', views.editarSitio, name='editarSitio'),
    url(r'^admin/editarAux/(?P<id>[0-9]+)$', views.editarSitioAux, name='editarSitioAux'),
    url(r'^admin/eliminar/(?P<id>[0-9]+)$', views.eliminarSitio, name='eliminarSitio'),
    url(r'^admin/eliminarAux/(?P<id>[0-9]+)$', views.eliminarSitioAux, name='eliminarSitioAux'),
    url(r'^admin/editarservicio/(?P<id>[0-9]+)$', views.editarServicio, name='editarServicio'),
    url(r'^admin/editarservicioAux/(?P<id>[0-9]+)$', views.editarServicioAux, name='editarServicioAux'),
    url(r'^admin/eliminarservicio/(?P<id>[0-9]+)$', views.eliminarServicio, name='eliminarServicio'),
    url(r'^admin/eliminarservicioAux/(?P<id>[0-9]+)$', views.eliminarServicioAux, name='eliminarServicioAux'),
    url(r'^admin/agregarEvento$', views.agregarEvento, name='agregarEvento'),
    url(r'^admin/editarEvento/(?P<id>[0-9]+)$', views.editarEvento, name='editarEvento'),
    url(r'^admin/editarEventoAux/(?P<id>[0-9]+)$', views.editarEventoAux, name='editarEventoAux'),
    url(r'^admin/eliminarevento/(?P<id>[0-9]+)$', views.eliminarEvento, name='eliminarEvento'),
    url(r'^admin/eliminareventoAux/(?P<id>[0-9]+)$', views.eliminarEventoAux, name='eliminarEventoAux'),

    
    ]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.db import connection
#from django.urls import reverse
from django.core.urlresolvers import reverse
from django.core.mail import send_mail

import os
import numpy as np
import Excel
import math
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import datetime
import threading

import cloudinary.uploader

cloudinary.config(
    cloud_name = 'poppycloud',
    api_key = '328358331617938',
    api_secret = 'z-7k70XpvP1dl1ZdiqVF0olXp7A'
)


def esTodoCero(datos):
    for i in datos:
        if i != 0:
            return False
    return True

def generarGrafico(nombre, datosGrafico):
    #plt.switch.backend y plt.close se usan para no generar errores de hilos en matplotlib
    plt.switch_backend('Agg')
    if not esTodoCero(datosGrafico):
        fig = plt.figure(u"Reacciones") # Figure
        ax = fig.add_subplot(111) # Axes
        nombres = ['Relevante', 'Indiferente', 'Emocionante']
        datos = [datosGrafico[0], datosGrafico[1], datosGrafico[2]]

            

        xx = range(len(datos))

        ax.bar(xx, datos, width=0.8, align='center')
        ax.set_xticks(xx)
        ax.set_xticklabels(nombres)

        plt.title("Reacciones para: "+nombre)

        plt.savefig("Grafico"+nombre+".png")
        imagen_subida = cloudinary.uploader.upload("Grafico"+nombre+".png")

        #obtiene la referencia que va a permitir mostrar la imagen en la aplicación
        imagen_subida_url = imagen_subida["secure_url"]

        plt.close()        

        return imagen_subida_url
    else:
        return None
    

def generarGraficoVisitas(nombre, datosGrafico):
    

    #plt.switch.backend y plt.close se usan para no generar errores de hilos en matplotlib
    plt.switch_backend('Agg')
    if not esTodoCero(datosGrafico):
        fig = plt.figure(u"Visitas") # Figure
        ax = fig.add_subplot(111) # Axes
        nombres = ['Visitas']
        datos = [datosGrafico[0]]

            

        xx = range(len(datos))

        ax.bar(xx, datos, width=0.4, align="edge")
        ax.set_xticks(xx)
        ax.set_xticklabels(nombres)

        plt.title("Visitas para: "+nombre)

        plt.savefig("Grafico"+nombre+".png")
        imagen_subida = cloudinary.uploader.upload("Grafico"+nombre+".png")

        #obtiene la referencia que va a permitir mostrar la imagen en la aplicación
        imagen_subida_url = imagen_subida["secure_url"]

        plt.close()


        return imagen_subida_url
    else:
        return None

def generarGraficos(lista_graficos, lista_graficos_fechas):

    contador = 0
    lista_direcciones = []
    print(lista_graficos)
    for i in lista_graficos_fechas:
        

        fecha = str(i.day)+"-"+str(i.month)+"-"+str(i.year)
        elemento = generarGrafico(fecha, lista_graficos[contador])
        if elemento != None:
            lista_direcciones.append(generarGrafico(fecha, lista_graficos[contador]))
        
        #plt.show()
        
        contador += 1

        #imagen_subida = cloudinary.uploader.upload(img)

        #obtiene la referencia que va a permitir mostrar la imagen en la aplicación
        #imagen_subida_url = imagen_subida["secure_url"]
    return lista_direcciones
    

def generarGraficosVisitas(lista_graficos, lista_graficos_fechas):

    contador = 0
    lista_direcciones = []
    print(lista_graficos)
    for i in lista_graficos_fechas:
        

        fecha = str(i.day)+"-"+str(i.month)+"-"+str(i.year)
        elemento = generarGraficoVisitas(fecha, lista_graficos[contador])
        if elemento != None:

            lista_direcciones.append(generarGraficoVisitas(fecha, lista_graficos[contador]))
        
        #plt.show()
        
        contador += 1

        #imagen_subida = cloudinary.uploader.upload(img)

        #obtiene la referencia que va a permitir mostrar la imagen en la aplicación
        #imagen_subida_url = imagen_subida["secure_url"]
    return lista_direcciones
    



def obtenerValoresGraficosVisitas(lista_graficos, visitas):
    largo_visitas = len(visitas)
    for i in range(largo_visitas):
        lista_graficos[i][0] = visitas[i][0]
    return lista_graficos
    
    
def obtenerValoresGraficos(lista_graficos, relevantes, indiferentes, emocionantes):
    largo_relevantes = len(relevantes)
    largo_indiferentes = len(indiferentes)
    largo_emocionantes = len(emocionantes)

    for i in range(largo_relevantes):
        lista_graficos[i][0] = relevantes[i][0]
    for i in range(largo_indiferentes):
        lista_graficos[i][1] = indiferentes[i][0]
    for i in range(largo_emocionantes):
        lista_graficos[i][2] = emocionantes[i][0]
    return lista_graficos


def obtenerFechas():
    lista = []
    lista.append(datetime.datetime.now())
    contador = 1
    while contador <= 6:
        lista.append(datetime.datetime.now() - datetime.timedelta(days=contador))
        contador += 1
    return lista

def obtenerValoresGraficosFechasVisitas(lista_graficos, visitas):
    largo_visitas = len(visitas)
    
    for i in range(largo_visitas):
        lista_graficos[i][0] = visitas[i][1]
    return lista_graficos

def obtenerValoresGraficosFechas(lista_graficos, relevantes, indiferentes, emocionantes):
    largo_relevantes = len(relevantes)
    largo_indiferentes = len(indiferentes)
    largo_emocionantes = len(emocionantes)

    for i in range(largo_relevantes):
        lista_graficos[i][0] = relevantes[i][1]
    for i in range(largo_indiferentes):
        lista_graficos[i][1] = indiferentes[i][1]
    for i in range(largo_emocionantes):
        lista_graficos[i][2] = emocionantes[i][1]
    return lista_graficos
    

def inicializarGraficosVisitas():
    return [[0],[0],[0],[0],[0],[0],[0]]
def inicializarGraficosReacciones():
    return [[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]

def enviarCorreosElectronicos():
    send_mail('Prueba de envío de correos varios usuarios', 'Im Poppy', 'pdjango123@gmail.com', ['dylanrodbar97@gmail.com', 'josemorar96@gmail.com ', 'karizp14@gmail.com '])
    

def convertir_tupla_lista(tupla):
    lista = []
    largo = len(tupla)
    for i in range(largo):
        lista.append(list(tupla[i]))
    return lista


def convertir_lista_tupla(lista):
    largo = len(lista)
    for i in range(largo):
        lista[i] = tuple(lista[i])
    lista = tuple(lista)
    return lista

def dividirListaGruposTres(lista):
    lista_retorno = []
    elemento_lista = []
    largo = len(lista)
    if largo <= 3:
        lista_retorno.append(lista)
        lista_retorno.append([])
    else:
        elemento_lista = lista[:3]
        lista_retorno.append(elemento_lista)
        lista_retorno.append(lista[3:])
    return lista_retorno


def dividirListaGruposCuatro(lista):
    lista_retorno = []
    elemento_lista = []
    largo = len(lista)
    if largo <= 4:
        lista_retorno.append(lista)
        lista_retorno.append([])
    else:
        while(largo > 4):
            elemento_lista = lista[:4]
            lista_retorno.append(elemento_lista)
            lista = lista[4:]
            largo = len(lista)
        lista_retorno.append(lista)
    return lista_retorno

def estadisticasVisitasAux(request):
    template = loader.get_template('home/admin.html')

    cur = connection.cursor()
    cur.callproc('obtener_sitios_interes', [])
    sitios = cur.fetchall()


    cur.nextset()

    cur.callproc('obtener_servicios', [])
    servicios = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_calendario', [])
    calendarios = cur.fetchall()
    cur.nextset()
    cur.callproc('obtener_visitas', [])
    visitas = cur.fetchall()
    
    cur.close

    inicio_valores = inicializarGraficosVisitas()
    valores_graficos = obtenerValoresGraficosVisitas(inicio_valores, visitas)
    valores_graficos_fechas = obtenerFechas()

    direcciones = generarGraficosVisitas(valores_graficos, valores_graficos_fechas)

    plt.close('all')
    
    context = {
        'sitiosinteres': sitios,
        'servicios': servicios,
        'calendarios': calendarios,
        'id': 0,
        'direcciones': direcciones
    }
    return HttpResponse(template.render(context, request))


def estadisticasVisitas(request):
    template = loader.get_template('home/admin.html')
    return HttpResponseRedirect(reverse('home:estadisticasVisitasAux'))

def estadisticasReaccionesAux(request):
    template = loader.get_template('home/admin.html')

    cur = connection.cursor()
    cur.callproc('obtener_sitios_interes', [])
    sitios = cur.fetchall()


    cur.nextset()

    cur.callproc('obtener_servicios', [])
    servicios = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_calendario', [])
    calendarios = cur.fetchall()
    cur.nextset()
    cur.callproc('obtener_relevantes', [])
    relevantes = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_indiferentes', [])
    indiferentes = cur.fetchall()
    
    cur.nextset()
    cur.callproc('obtener_emocionantes', [])
    emocionantes = cur.fetchall()
    
    cur.close

    inicio_valores = inicializarGraficosReacciones()
    valores_graficos = obtenerValoresGraficos(inicio_valores, relevantes, indiferentes, emocionantes)
    valores_graficos_fechas = obtenerFechas()

    
    direcciones = generarGraficos(valores_graficos, valores_graficos_fechas)
    
    plt.close('all')

    context = {
        'sitiosinteres': sitios,
        'servicios': servicios,
        'calendarios': calendarios,
        'id': 0,
        'direcciones': direcciones
    }
    return HttpResponse(template.render(context, request))


def estadisticasReacciones(request):
    template = loader.get_template('home/admin.html')
    return HttpResponseRedirect(reverse('home:estadisticasReaccionesAux'))

    

def index(request):

home/templates/home/editarcalendario.html
                <div class="modal-content">           
                        <div class="modal-body" style="padding:40px 50px;">                
            
                            <form class="form-signin" method='POST' action='{% url 'home:editarEventoAux' id %}'  > {% csrf_token %}
                                <h1 align="center">Calendario</h1>
                                <br>
                                <h4>Ingrese la nueva fecha, titulo y descripcion</h4>
                                <br>
                                <input type="date" name="fecha-evento" required>
                                <br>
                                <br>
                                <label for="EditNameSitio" class="sr-only">Correo</label>
                                <input type="text" id="input" name="nombre-evento" class="form-control" placeholder="Nombre..." required autofocus>
                                <br>
                                <div class="form-group">
                                        <label for="EditDescriptionSitio"></label>
                                        <textarea class="form-control" name="descripcion-evento" rows="5" id="comment" placeholder="Descripcion..."></textarea>
                                </div>
                                <br>
                                <button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button>
                          </form>
                        </div>
                </div>

home/templates/home/editarservicio.html
<!-- Modal content-->
<div class="modal-content">           
        <div class="modal-body" style="padding:40px 50px;">                
                <form class="form-signin" method='POST' action='{% url 'home:editarServicioAux' id %}'  > {% csrf_token %}
                    <h1 align="center">Servicios</h1>
                    <br>
                    <h4>Ingrese el nuevo nombre y descripcion</h4>
                    <br>
                    <label for="EditNameSitio" class="sr-only">Correo</label>
                    <input type="text" id="input" class="form-control" name="titulo" placeholder="Nombre..." required autofocus>
                    <br>
                    <div class="form-group">
                            <label for="EditDescriptionSitio"></label>
                            <textarea class="form-control" rows="5" id="comment" name="descripcion" placeholder="Descripcion..."></textarea>
                    </div>
                    <br>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button>
              </form>      
        </div>
    </div>    

home/templates/home/editarsitio.html
{% block content %}
{% load staticfiles %}



                <div class="modal-content">           
                  <div class="modal-body" style="padding:40px 50px;">                
            
                    <form class="form-signin" method='POST' action='{% url 'home:editarSitioAux' id %}'  > {% csrf_token %}
                        <h1 align="center">Sitios de interes</h1>
                        <br>
                        <h4>Ingrese el nuevo nombre y descripcion</h4>
                        <br>
                        <label for="EditNameSitio" class="sr-only">Correo</label>
                        <input type="text" id="input" name="titulo" class="form-control" placeholder="Nombre..." required autofocus>
                        <br>
                        <div class="form-group">
                                <label for="EditDescriptionSitio"></label>
                                <textarea class="form-control" rows="5" id="comment" name="descripcion" placeholder="Descripcion..."></textarea>
                        </div>
                        <br>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button>
                  </form>     
                </div>
        </div> 
           

{% endblock %}

home/templates/home/eliminarcalendario.html
<div class="modal-content">
            
                
        <!-- Modal body -->
        <div class="modal-body">
            <h1 align="center">Calendario</h1><br>
            <h4>Esta seguro que quiere eliminar el evento del calendario</h4>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
                <a type="submit" href="/inicio/admin/eliminareventoAux/{{id}}">
                
                    <button type="submit"  class="btn btn-danger">Eliminar <span></span></button>    
                
                </a>    
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        </div>
        
    </div>

home/templates/home/eliminarservicio.html
<div class="modal-content">
        
            
        <!-- Modal body -->
        <div class="modal-body">
            <h1 align="center">Servicio</h1><br>
            <h4>Esta seguro que quiere eliminar el servicio</h4>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
                <a type="submit" href="/inicio/admin/eliminarservicioAux/{{id}}">
                
                    <button type="submit"  class="btn btn-danger">Eliminar <span></span></button>    
                
                </a>    
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        </div>
        
    </div>

home/templates/home/eliminarsitio.html
<div class="modal-content">
                
                    
    <!-- Modal body -->
    <div class="modal-body">
        <h1 align="center">Sitio de Interes</h1>
        <br>
        <h4>Esta seguro que quiere eliminar el sitio de interes</h4>
    </div>
    
    <!-- Modal footer -->
    <div class="modal-footer">
        
        <a type="submit" href="/inicio/admin/eliminarAux/{{id}}">
                
            <button type="submit"  class="btn btn-danger">Eliminar <span></span></button>    
        
        </a>
        
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    </div>
    
</div>

home/templates/home/header.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>EICO</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'home/css/card.css' %}" type = "text/css"/>

    <!-- <script src="{%static 'home/js/bootstrap.min.js' %}"></script> !-->
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">


    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>

            
            .jumbotron { 
                background-color: #2471A3   ; 
                color: #ffffff;
            }

            .navbar {
                margin-bottom: 0;
                background-color: #2471A3   ;
                z-index: 9999;
                border: 0;
                font-size: 12px !important;
                line-height: 1.42857143 !important;
                letter-spacing: 4px;
                border-radius: 0;
            }

            .navbar li a, .navbar .navbar-brand {
                color: #fff !important;
            }

            .navbar-nav li a:hover, .navbar-nav li.active a {
                color: #2471A3    !important;
                background-color: #fff !important;
            }

            .navbar-default .navbar-toggle {
                border-color: transparent;
                color: #fff !important;
            }

        

            .jumbotron {
                font-family: Montserrat, sans-serif;
            }

            .navbar {
                font-family: Montserrat, sans-serif;
            }


            .carousel-inner img {
                width: 100%; /* Set width to 100% */
                max-height: 600px;
                margin: auto;
            }

            .carousel-caption h3 {
                color: #fff !important;
            }

            @media (max-width: 600px) {
                .carousel-caption {
                    display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
                }
            }


            footer {
                background-color: #2471A3 ;
                color: #f5f5f5;
                padding: 32px;
            }

            footer a {
                color: #f5f5f5;
            }

            footer a:hover {
                color: #777;
                text-decoration: none;
            }
            </style>
            

    </style>


</head>

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
        </button>
        <a class="navbar-brand" href="/inicio">EICO</a>
        </div>
        
        <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="/foro/escuela">ESCUELA</a></li>
            <li><a href="/foro/egresado">GRADUADOS</a></li>
            <li><a href="/inicio/servicio">SERVICIOS</a></li>
            <li><a href="/inicio/interes">SITIOS DE INTERES</a></li>
            <li><a href="/calendario">CALENDARIO</a></li>
            {% if request.session.TipoUsuario == "Administrador" or request.session.TipoUsuario == "Director" %}
            <li><a href="/inicio/admin">ADMINISTRADOR</a></li>
            {% endif %}

            
          <!--  <li><a href="#contact">ADMINISTRADOR</a></li> !--> 
            {% if not request.session.Usuario %}
                <li><a href='#' data-toggle="modal" data-target="#Login"><span class="glyphicon glyphicon-log-in"></span></a></li>
            {% endif %}

            {% if request.session.Usuario %}
                <li><a href="/perfil"><span class="glyphicon glyphicon-user"></span></a></li>
                <li><a href='/inicio/logout/' data-toggle="modal" data-target="/inicio/logout/"><span class="glyphicon glyphicon-log-out"></span></a></li>
            {% endif %}
        </ul>
        </div>
        
    </div>
    </nav>
                  
    <div>
        {% block content %}
        {% endblock %}
    </div>

    <footer class="text-center">
            <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
            </a><br><br>
            <p>Hecho por estudiantes de ingenieria en computacion </p> 
          </footer>


<!--
     Modal Login
<div class="modal fade" id="Login" role="dialog" style="padding-top:150px;">
    <div class="modal-dialog">
        Modal conten
        <div class="modal-content">           
            <div class="modal-body" style="padding:40px 50px;">                
                    <form class="form-signin" method='POST' action= '{% url 'home:login' %}'  > {% csrf_token %}
                        <h1 align="center">EICO</h1>
                        <br>
                        <h4>Ingrese su correo y contraseña</h4>
                        <br>
                        <label for="inputEmail" class="sr-only">Correo</label>
                        <input type="email" id="inputEmail" name="email" class="form-control" placeholder="Correo..." required autofocus>
                        <br>
                        <label for="inputPassword" class="sr-only">Contraseña</label>
                        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Contraseña.." required>
                        <br>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
                  </form>      
            </div>
        </div>    
    </div>
</div> 

-->

<!-- Modal Login -->
<div class="modal fade" id="Login" role="dialog" style="padding-top:150px;">
    <div class="modal-dialog">
        <!-- Modal content-->   
        <div class="modal-content">           
            <div class="modal-body" style="padding:40px 50px;"> 
                    <ul  class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#ingresar">Ingresar</a></li>
                            <li><a data-toggle="tab" href="#registrar">Solicitar Usuario</a></li>
                    </ul>    
                    <div class="tab-content">
                    <div id="ingresar" class="tab-pane fade in active">
                        <br>
                        <form class="form-signin"  method='POST' action= '{% url 'home:login' %}'  > {% csrf_token %}
                            <h1 align="center">EICO</h1>
                            <br>
                            <h4>Ingrese su correo y contraseña</h4>
                            <br>
                            <label for="inputEmail" class="sr-only">Correo</label>
                            <input type="email" id="inputEmail" class="form-control" name="email" placeholder="Correo..." required autofocus>
                            <br>
                            <label for="inputPassword" class="sr-only">Contraseña</label>
                            <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Contraseña.." required>
                            <br>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
                        </form>   
     
                    </div>
                    <div id="registrar" class="tab-pane fade">
                        <br>
                            <form class="form-signin" method='POST' action= '{% url 'home:solicitarUsuario' %}'  > {% csrf_token %}
                                    <h1 align="center">EICO</h1>
                                    <br>
                                    <h4>Ingrese su nombre, correo y descripcion de porque quiere unirse al foro</h4>
                                    <br>
                                    <label for="inputEmail"  class="sr-only">Nombre</label>
                                    <input type="text" id="inputEmail" name="nombresolicitud" class="form-control" placeholder="Nombre..." required autofocus>
                                    <br>
                                    <label for="inputEmail" class="sr-only">Correo</label>
                                    <input type="email" id="inputEmail" name="emailsolicitud" class="form-control" placeholder="Correo..." required autofocus>
                                    <br>
                                    <textarea class="form-control" name="descripcionsolicitud" rows="6" id="descripcion" required name="Descripcion"></textarea>
                                    <br>
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">Enviar Solicitud</button>
                                </form>  
                    </div>
                    </div>

            </div>
        </div>    
    </div>
</div>         



</body>
</html>