EICO/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^inicio/', include('home.urls', namespace="home")),
    url(r'^foro/', include('forum.urls', namespace="forum")),
    url(r'^calendario/', include('eicocalendar.urls', namespace="calendario")),
    url(r'^perfil/', include('personal.urls', namespace="perfil")),
]

forum/urls.py
from django.conf.urls import url, include
from . import views


app_name = "forum"

urlpatterns = [ 
                url(r'^escuela/$', views.viewEscuela, name='viewEscuela'),
                url(r'^escuela/nueva$', views.newEscuela, name='newEscuela'),
                
                url(r'^egresado/$', views.viewEgresado, name='viewEgresado'),  
                url(r'^egresado/nueva$', views.newEgresado, name='newEgresado'), 

                url(r'^insertarPost/$', views.insertarPost, name='insertarPost'),

                url(r'^changePost/(?P<id>[0-9]+)/$', views.changePost, name='changePost'),

                url(r'^editar/(?P<id>[0-9]+)/$', views.editNoticia, name="editNoticia"),

                url(r'^eliminar/(?P<id>[0-9]+)/$', views.deleteNoticia, name="deleteNoticia"),

                url(r'^eliminar/(?P<id>[0-9]+)/$', views.deleteNoticia, name="deleteNoticia"),

                url(r'^eliminar/eliminarpublicacionAux/(?P<id>[0-9]+)/$', views.eliminarPublicacionAux, name="eliminarPublicacionAux"),


                url(r'^noticia/calificarrelevante/(?P<id>[0-9]+)/$', views.calificarNoticiaRelevante, name="calificarNoticiaRelevante"),

                url(r'^noticia/calificarindiferente/(?P<id>[0-9]+)/$', views.calificarNoticiaIndiferente, name="calificarNoticiaIndiferente"),

                url(r'^noticia/calificaremocionante/(?P<id>[0-9]+)/$', views.calificarNoticiaEmocionante, name="calificarNoticiaEmocionante"),

                url(r'^ver/(?P<id>[0-9]+)/$', views.viewNoticia, name="viewNoticia"),

                url(r'^insertarComentario/(?P<id>[0-9]+)/$', views.insertarComentario, name="insertarComentario"),

                url(r'^escuela/anteriorescuela/$', views.anteriorEscuela, name="anteriorEscuela"),
                url(r'^escuela/siguienteescuela/$', views.siguienteEscuela, name="siguienteEscuela"),
                url(r'^egresados/anterioregresados/$', views.anteriorEgresados, name="anteriorEgresados"),
                url(r'^egresados/siguienteegresados/$', views.siguienteEgresados, name="siguienteEgresados"),

                url(r'^buscarUsuarioEscuela/$', views.buscarUsuarioEscuela, name="buscarUsuarioEscuela"),
                url(r'^buscarUsuarioEgresado/$', views.buscarUsuarioEgresado, name="buscarUsuarioEgresado"),
                url(r'^buscarNoticiaEscuela/$', views.buscarNoticiaEscuela, name="buscarNoticiaEscuela"),
                url(r'^buscarNoticiaEgresado/$', views.buscarNoticiaEgresado, name="buscarNoticiaEgresado"),
                
                
                
                              
            ]

forum/models.py
from django.db import models

# Create your models here.

forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.db import connection
#from django.urls import reverse
from django.core.urlresolvers import reverse
from django.core.mail import send_mail


import cloudinary.uploader
import math

cloudinary.config(
    cloud_name = 'poppycloud',
    api_key = '328358331617938',
    api_secret = 'z-7k70XpvP1dl1ZdiqVF0olXp7A'
)

def convertir_tupla_lista(tupla):
    lista = []
    largo = len(tupla)
    for i in range(largo):
        lista.append(list(tupla[i]))
    return lista


def convertir_lista_tupla(lista):
    largo = len(lista)
    for i in range(largo):
        lista[i] = tuple(lista[i])
    lista = tuple(lista)
    return lista
    

def viewEscuela(request):
    template = loader.get_template('forum/escuela.html')

    request.session['CuentaPublicaciones'] = 0
    numero_fila = request.session['CuentaPublicaciones']
    
    numero_fila = numero_fila * 4

    cur = connection.cursor()
    cur.callproc('obtener_publicaciones_escuela', [numero_fila])
    noticias = cur.fetchall()

    cur.nextset()

    cur.callproc('obtener_todas_publicaciones_escuela', [])
    publicaciones_todas = cur.fetchall()
    cur.nextset()
    cur.callproc('obtener_top_publicaciones_relevantes_escuela', [])
    
    noticias_relevantes = cur.fetchall()

    
    lista = convertir_tupla_lista(noticias)

    largo_noticias = len(lista)

    
    for i in range(largo_noticias):
        indice = lista[i]
        id_c = indice[0]
        cur.nextset()
        cur.callproc('obtener_relevante_publicacion', [id_c])
        cantidad_relevantes = cur.fetchall()
        elemento = cantidad_relevantes[0][0]
        lista[i].append(elemento)

    noticias = convertir_lista_tupla(lista)

    cur.nextset()
    cur.close

    largo_noticias_todas = len(publicaciones_todas)
    numero_grupos = math.ceil((largo_noticias_todas / 4))
    request.session['LimitePublicaciones'] = numero_grupos
    
    
    
    context = {
   	    'noticias': noticias,
        'noticiasrelevantes': noticias_relevantes
    }
    return HttpResponse(template.render(context, request))

    #return render(request, 'forum/escuela.html')

def viewEgresado(request):
    template = loader.get_template('forum/egresado.html')

    request.session['CuentaPublicaciones'] = 0
    numero_fila = request.session['CuentaPublicaciones']
    
    numero_fila = numero_fila * 4

    cur = connection.cursor()
    cur.callproc('obtener_publicaciones_egresados', [numero_fila])
    noticias = cur.fetchall()

    cur.nextset()

    cur.callproc('obtener_todas_publicaciones_egresados', [])
    publicaciones_todas = cur.fetchall()
    cur.nextset()
    cur.callproc('obtener_top_publicaciones_relevantes_egresados', [])
    
    noticias_relevantes = cur.fetchall()

    
    lista = convertir_tupla_lista(noticias)

    largo_noticias = len(lista)

    
    for i in range(largo_noticias):
        indice = lista[i]
        id_c = indice[0]
        cur.nextset()
        cur.callproc('obtener_relevante_publicacion', [id_c])
        cantidad_relevantes = cur.fetchall()
        elemento = cantidad_relevantes[0][0]
        lista[i].append(elemento)

    noticias = convertir_lista_tupla(lista)

    cur.nextset()
    cur.close

    largo_noticias_todas = len(publicaciones_todas)
    numero_grupos = math.ceil((largo_noticias_todas / 4))
    request.session['LimitePublicaciones'] = numero_grupos
    
    
    
    context = {
   	    'egresados': noticias,
        'noticiasrelevantes': noticias_relevantes
    }
    return HttpResponse(template.render(context, request))
    #return render(request, 'forum/egresado.html')

def newEgresado(request):
	return render(request, 'forum/nuevaNoticia.html')

def newEscuela(request):
	return render(request, 'forum/nuevaNoticia.html')

def insertarPost(request):

    template = loader.get_template('forum/nuevaNoticia.html')

    titulo = request.POST.get('titulo')
    descripcion = request.POST.get('descripcion')
    link_video = request.POST.get('video')
    file = request.FILES.get("archivo")

    embed_link_video = link_video.replace("watch?v=", "embed/")

    user = int(request.session['Usuario'])

    imagen_subida = cloudinary.uploader.upload(file)

    #obtiene la referencia que va a permitir mostrar la imagen en la aplicación
    imagen_subida_url = imagen_subida["secure_url"]

    cur = connection.cursor()
    cur.callproc('insertar_publicacion', [titulo, descripcion, embed_link_video, imagen_subida_url, user])
    cur.nextset()
    cur.callproc('obtener_correos_electronicos_sin_administradores', [])
    correos = cur.fetchall()
    cur.close
    
    lista_correos = []
    largo = len(correos)
    for i in range(largo):
        lista_correos.append(correos[i][0])

    seccion = "Escuela"
    if request.session['TipoUsuario'] == "Egresado":
        seccion = "Egresados"


    mensaje = "Notificación de una nueva noticia en la sección de: "+seccion+". Título: "+titulo
    
    send_mail('Notificación de nueva noticia',
             mensaje, 
             'eicocuenta@gmail.com',
             lista_correos)

    
    return HttpResponseRedirect(reverse('forum:viewEscuela'))


def viewNoticia(request, id):

    template = loader.get_template('forum/detalleNoticia.html')

    cur = connection.cursor()
    cur.callproc('obtener_publicacion_id', [id, ])
    publicacion = cur.fetchall()

    cur.nextset()


    cur.callproc('obtener_comentarios_publicacion', [id, ])
    comentarios = cur.fetchall()

    cur.nextset()

    cur.callproc('obtener_relevante_publicacion', [id, ])

    relevantes = cur.fetchall()

    cur.nextset()

    cur.callproc('obtener_indiferente_publicacion', [id, ])

    indiferentes = cur.fetchall()

    cur.nextset()

    cur.callproc('obtener_emocionante_publicacion', [id, ])

    emocionantes = cur.fetchall()

    cur.close()

    
    context = {
        'publicacion': publicacion[0],
        'comentarios': comentarios,
        'relevantes': relevantes[0],
        'indiferentes': indiferentes[0],
        'emocionantes': emocionantes[0],
        'id': id
    }

    return HttpResponse(template.render(context, request))



def editNoticia(request, id):
    template = loader.get_template('forum/editarNoticia.html')
    context = {
        "id": id,

    }
    return HttpResponse(template.render(context, request))


def changePost(request, id):
    template = loader.get_template('forum/editarNoticia.html')

    titulo = request.POST.get('titulo')
    descripcion = request.POST.get('descripcion')
    link_video = request.POST.get('video')
    file = request.FILES.get("archivo")

    embed_link_video = link_video.replace("watch?v=", "embed/")

    user = int(request.session['Usuario'])

    imagen_subida = cloudinary.uploader.upload(file)

    # obtiene la referencia que va a permitir mostrar la imagen en la aplicación
    imagen_subida_url = imagen_subida["secure_url"]

    cur = connection.cursor()
    cur.callproc('editar_publicacion', [id, titulo, descripcion, embed_link_video, imagen_subida_url])
    cur.close

    return HttpResponseRedirect(reverse('perfil:viewProfile'))




def deleteNoticia(request, id):
    template = loader.get_template('forum/eliminarpublicacion.html')
    
    context = {
        'id': id
    }
    
    return HttpResponse(template.render(context, request))
    
def eliminarPublicacionAux(request, id):
    template = loader.get_template('forum/eliminarpublicacion.html')

    cur = connection.cursor()
    cur.callproc('eliminar_publicacion', [id,])
    cur.close

    return HttpResponseRedirect(reverse('perfil:viewProfile'))


def insertarComentario(request, id):
    template = loader.get_template('forum/detalleNoticia.html')

    print("ENTRA A COMENTARIOS")
    id_usuario = int(request.session['Usuario'])
    id_publicacion = id
    comentario = request.POST.get('comentario')

    cur = connection.cursor()
    cur.callproc('insertar_comentario_publicacion', [comentario, id_usuario, id_publicacion])
    cur.close

    #return HttpResponseRedirect("") 
    #redirect_to = reverse('forum:viewNoticia', kwargs={'id': id})
    #return redirect(redirect_to)
    #return HttpResponseRedirect(viewNoticia, id)
    return HttpResponseRedirect(reverse('forum:viewNoticia', args=[id]))

def calificarNoticiaRelevante(request, id):
    template = loader.get_template('forum/detalleNoticia.html')

    id_usuario = int(request.session['Usuario'])
    id_publicacion = id
    calificacion = "Relevante"

    cur = connection.cursor()
    cur.callproc('obtener_id_calificacion', [calificacion,])
    id_calificacion_tupla = cur.fetchall()
    

    id_calificacion = id_calificacion_tupla[0][0]

    
    cur.nextset()
    cur.callproc('calificar_publicacion', [id_publicacion,id_calificacion,id_usuario])

    cur.close

    return HttpResponseRedirect(reverse('forum:viewNoticia', args=[id])) 


def calificarNoticiaIndiferente(request, id):
    template = loader.get_template('forum/detalleNoticia.html')

    id_usuario = int(request.session['Usuario'])
    id_publicacion = id
    calificacion = "Indiferente"

    cur = connection.cursor()
    cur.callproc('obtener_id_calificacion', [calificacion,])
    id_calificacion_tupla = cur.fetchall()
    

    id_calificacion = id_calificacion_tupla[0][0]

    
    cur.nextset()
    cur.callproc('calificar_publicacion', [id_publicacion,id_calificacion,id_usuario])

    cur.close

    return HttpResponseRedirect(reverse('forum:viewNoticia', args=[id])) 


def calificarNoticiaEmocionante(request, id):
    template = loader.get_template('forum/detalleNoticia.html')

    id_usuario = int(request.session['Usuario'])
    id_publicacion = id
    calificacion = "Emocionante"

    cur = connection.cursor()
    cur.callproc('obtener_id_calificacion', [calificacion,])
    id_calificacion_tupla = cur.fetchall()
    

forum/templates/forum/detalleNoticia.html
{% extends "home/header.html" %}

{% block content %}
{% load staticfiles %}

<div class="container" style="margin-top:100px; margin-bottom:100px;">

        <div class="w3-row">
            

             <div class="w3-card-4 w3-margin w3-white">
                <img src={{ publicacion.4  }} alt="Noticia" style="width:100% ; max-height:400px">

                {% if request.session.Usuario %}
                <div class="text-right">
                    <div class="row" style="margin-top:10px; margin-right:10px;">
                            <a href="/foro/noticia/calificarrelevante/{{id}}">
                                <button class="btn" style="margin-bottom:10px;"><span class="glyphicon glyphicon-star" aria-hidden="true"></span> Relevante
                                    <span class="badge">{{relevantes.0}}</span>
                                </button>
                            </a>
                            <a href="/foro/noticia/calificarindiferente/{{id}}">
                                <button class="btn" style="margin-bottom:10px;"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Indiferente
                                    <span class="badge">{{indiferentes.0}}</span>
                                </button>
                            </a>
                            <a href="/foro/noticia/calificaremocionante/{{id}}">   
                                <button class="btn" style="margin-bottom:10px;"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span> Emocionante
                                    <span class="badge">{{emocionantes.0}}</span>
                                </button>
                            </a>   
                    </div>   
                 </div> 
                 {% endif %}            
                
               
                    
                <div class="w3-container">
                  <h3><b>{{publicacion.0}}</b></h3>
                    <h5>Autor de la notica, <a href="/perfil/ajeno/{{publicacion.6}}">{{ publicacion.5 }}</a> <span class="w3-opacity">{{ post.3|date:"d-m-Y" }}</span></h5>
                  
                </div>
            
                <div class="w3-container">
                    {{ publicacion.1 }}
                </div>

                <br>
                <br>
                
                <div class="embed-responsive embed-responsive-16by9" style="margin-right:20px;margin-left:20px;">
                        <iframe class="embed-responsive-item" src={{ publicacion.2 }}></iframe>
                </div>

                <br>

              </div>

              <br>
              <br>

              {% if request.session.Usuario %}
              <h4>Deja un comentario</h4>
                <form role="form" method='POST' enctype="multipart/form-data" action='{% url 'forum:insertarComentario' id %}'  >  {% csrf_token %}
                    <div class="form-group">
                    <textarea class="form-control" name="comentario" rows="6" style="resize: none;"required></textarea>
                    </div>
                    <div align="right">
                        
                            <button type="submit" class="btn" style="background-color:#2471A3; color:white;">Enviar</button>
                    </div>
                </form>
                {% endif %}
                
                <p>Comentarios:</p><br>

                <ul class="list-group">
                    <div id="list" style="height: auto; max-height: 450px; overflow-x: hidden;">
                        
                    {% for i in comentarios %}
                    <li class="list-group-item" style="border: none">
                        <div class="media">
                            <div class="media-left">
                                <a href="/perfil/ajeno/{{i.4}}">
                                <img src={{ i.3 }} class="img-circle" style="width:60px">
                                <a/>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">{{ i.2 }} <small><i>{{ i.1|date:"d-m-Y" }}</i></small></h4>
                                <p>
                                    {{ i.0 }}
                                </p>
                            </div>
                        </div>
                        <br>
                    </li>
               
                    {% endfor %}

                </div>
            </ul>
          
        </div>

</div>

{% endblock %}

forum/templates/forum/egresado.html
{% extends "home/header.html" %}

{% block content %}
{% load staticfiles %}
<div class="w3-content" style="max-width:1400px">

        <header class="w3-container w3-center w3-padding-32"> 
            <br><br>
            <h1><b>GRADUADOS</b></h1>
        </header>

        {% if  request.session.TipoUsuario == "Graduado" or request.session.TipoUsuario == "Director" %}
        <div class="row">
                <div class="col-md-8" align="right">      
                    <a href="/foro/egresado/nueva">
                        <button type="button" class="btn btn-default">Nueva publicacion <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>                           
                    </a>
                </div>
        </div>
        {% endif %}
<!-- Grid -->
<div class="w3-row">

        <!-- Noticias -->
        <div class="w3-col l8 s12">
          {% for post in egresados %}
          <!-- Noticia 1 -->
          <div class="w3-card-4 w3-margin w3-white">
            <img src={{ post.4  }} alt="Noticia" style="width:100% ; max-height:400px">
            <div class="w3-container">
              <h3><b>{{ post.1 }}</b></h3>
              <h5>{{ post.2 }}, <span class="w3-opacity">{{ post.3|date:"d-m-Y" }}</span></h5>
            </div>
        
            <div class="w3-container">
              <p>{{ post.6 }}</p>
              <div class="w3-row">
                <div class="w3-col m8 s12">
                  <a href="/foro/ver/{{post.0}}">
                  
                    <p><button class="w3-button w3-padding-large w3-white w3-border"><b>MAS INFORMACION »</b></button></p>
                  </a>
                </div>
                <div class="w3-col m4 w3-hide-small">
                  <p><span class="w3-padding-large w3-right"><b>Relevante  </b> <span class="w3-tag">{{post.7}}</span></span></p>
                </div>
              </div>
            </div>
          </div>
          
          <hr>
          {% endfor %}
        
          
        <!-- Fin de publicaciones -->
        <!-- Anterior - Siguiente  -->
        <nav aria-label="...">
                <ul class="pager">
                  <li><a href="/foro/egresados/anterioregresados/">Anterior</a></li>
                  <li><a href="/foro/egresados/siguienteegresados/">Siguiente</a></li>
                </ul>
        </nav>

        </div>
         <!-- Fin de Noticias -->

<!-- Buscador - Noticias populares -->
<div class="w3-col l4">
     <!-- Buscador -->
        <div class="w3-card w3-margin w3-margin-top">
            <form class="form-inline" style="margin-top: 10px; margin-bottom: 20px;" method='POST' enctype="multipart/form-data" action='{% url 'forum:buscarNoticiaEgresado'  %}'  >  {% csrf_token %}
              <div class="input-group">
                <input type="text" class="form-control" name="nombrenoticia" size="50" placeholder="Buscar noticia..." required>
                <div class="input-group-btn" >
                          
                      <button  class="btn btn-default btn-sm" data-target="#Buscar_Usuario"><span class="glyphicon glyphicon-search" ></span></button>
                    
                </div>
              </div>
        </form>
     
        
                      <form class="form-inline" style="margin-top: 10px; margin-bottom: 20px;" method='POST' enctype="multipart/form-data" action='{% url 'forum:buscarUsuarioEgresado'  %}'  >  {% csrf_token %}
                        <div class="input-group">
                          <input type="text" class="form-control" name="nombreusuario" size="50" placeholder="Buscar usuario..." required>
                          <div class="input-group-btn" >
                                    
                                <button  class="btn btn-default btn-sm" data-target="#Buscar_Usuario"><span class="glyphicon glyphicon-search" ></span></button>
                              
                          </div>
                        </div>
                  </form>



              
      </div><hr>
        
        <!-- Noticas populares -->
        <div class="w3-card w3-margin">
          <div class="w3-container w3-padding">
            <h4>Noticias Populares</h4>
          </div>
          <ul class="w3-ul w3-hoverable w3-white">
              {% for post in noticiasrelevantes %}
              <li class="w3-padding-16">
                <a href="/foro/ver/{{post.4}}">
              
                  <img src={{post.2}} alt="Image" class="w3-left w3-margin-right" style="height:50px; width: 50px">
                </a>
                <span class="w3-large">{{post.1}}</span><br>
                <span>{{post.3}}</span>
              </li>
              {% endfor %}  
            </ul>
        </div>
        <hr> 

</div>
</div>

<div class="modal fade" id="Buscar_Usuario" role="dialog" style="padding-top:150px;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">     
               
            <div class="modal-body" style="padding:40px 50px;"> 
                <h1>Resultados de la busqueda</h1>   
              <ul class="w3-ul w3-hoverable w3-white">               
                {% for i in "x"|rjust:"5" %}
                <li class="w3-padding-16">
                  <img src="{% static 'home/img/img5.jpg' %}" alt="Image" class="w3-left w3-margin-right" style="width:50px">
                  <span class="w3-large">Username</span><br>
                </li>
              {% endfor %}
              </ul>
            </div>
        </div>    
    </div>
  </div>

{% endblock %}

forum/templates/forum/eliminarpublicacion.html
<div class="modal-content">
            
                
    <!-- Modal body -->
    <div class="modal-body">
        <h1 align="center">Publicación</h1><br>
        <h4>Esta seguro que quiere eliminar la publicación</h4>
    </div>
    
    <!-- Modal footer -->
    <div class="modal-footer">
            <a type="submit" href="/foro/eliminar/eliminarpublicacionAux/{{id}}">
            
                <button type="submit"  class="btn btn-danger">Eliminar <span></span></button>    
            
            </a>    
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    </div>
    
</div>

forum/templates/forum/escuela.html
{% extends "home/header.html" %}

{% block content %}
{% load staticfiles %}
<div class="w3-content" style="max-width:1400px">

        <header class="w3-container w3-center w3-padding-32"> 
            <br><br>
            <h1><b>EICO</b></h1>
        </header>

        {% if request.session.TipoUsuario == "Estudiante" or request.session.TipoUsuario == "Funcionario" or request.session.TipoUsuario == "Director" %}
            
        <div class="row">
                <div class="col-md-8" align="right">      
                    <a href="/foro/escuela/nueva">
                        <button type="button" class="btn btn-default">Nueva publicacion <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>                           
                    </a>
                </div>
        </div>
        {% endif %}
<!-- Grid -->
<div class="w3-row">

        <!-- Noticias -->
        <div class="w3-col l8 s12">
          <!-- Noticia 1 -->
          {% for post in noticias %}
          <div class="w3-card-4 w3-margin w3-white">
            <img src={{ post.4  }} alt="Noticia" style="width:100% ; max-height:400px">
            <div class="w3-container">
              <h3><b>{{ post.1 }}</b></h3>
              <h5>{{ post.2 }}, <span class="w3-opacity">{{ post.3|date:"d-m-Y" }}</span></h5>
            </div>
        
            <div class="w3-container">
              <p>{{ post.6 }}</p>
              <div class="w3-row">
                <div class="w3-col m8 s12">
                  <a href="/foro/ver/{{post.0}}">
                    <p><button class="w3-button w3-padding-large w3-white w3-border"><b>MAS INFORMACION »</b></button></p>
                  </a>
                </div>
                <div class="w3-col m4 w3-hide-small">
                  <p><span class="w3-padding-large w3-right"><b>Relevante  </b> <span class="w3-tag">{{post.7}}</span></span></p>
                </div>
              </div>
            </div>
          </div>
          <hr>
        
          {% endfor %}
        <!-- Fin de noticias -->
        <nav aria-label="...">
                <ul class="pager">
                  <li><a href="/foro/escuela/anteriorescuela/">Anterior</a></li>
                  <li><a href="/foro/escuela/siguienteescuela/">Siguiente</a></li>
                </ul>
        </nav>

        </div>

<!-- Buscador -->
<div class="w3-col l4">
        <!-- About Card -->
        <div class="w3-card w3-margin w3-margin-top" >
            <form class="form-inline" style="margin-top: 10px; margin-bottom: 20px;" method='POST' enctype="multipart/form-data" action='{% url 'forum:buscarNoticiaEscuela'  %}'  >  {% csrf_token %}
              <div class="input-group">
                <input type="text" class="form-control" name="nombrenoticia" size="50" placeholder="Buscar noticia..." required>
                <div class="input-group-btn" >
                          
                      <button  class="btn btn-default"><span class="glyphicon glyphicon-search" ></span></button>
                    
                </div>
              </div>
        </form>

                      
        
        <form class="form-inline" style="margin-top: 10px; margin-bottom: 20px;" method='POST' enctype="multipart/form-data" action='{% url 'forum:buscarUsuarioEscuela'  %}'  >  {% csrf_token %}
            <div class="input-group">
              <input type="text" class="form-control" name="nombreusuario" size="50" placeholder="Buscar usuario..." required>
              <div class="input-group-btn" >
                        
                    <button   class="btn btn-default"><span  class="glyphicon glyphicon-search" ></span></button>
                  
              </div>
            </div>
      </form>

      


              
      </div>
        <hr>
        
        <!-- Noticas populares -->
        <div class="w3-card w3-margin">
          <div class="w3-container w3-padding">
            <h4>Noticias Populares</h4>
          </div>
          <ul class="w3-ul w3-hoverable w3-white">
            {% for post in noticiasrelevantes %}
            <li class="w3-padding-16">
              <a href="/foro/ver/{{post.4}}">
                <img src={{post.2}} alt="Image" class="w3-left w3-margin-right" style="height:50px; width: 50px">
              </a>
              <span class="w3-large">{{post.1}}</span><br>
              <span>{{post.3}}</span>
            </li>
            {% endfor %}  
          </ul>
        </div>
        <hr> 

</div>
</div>

<div class="modal fade" id="Buscar_Usuario" role="dialog" style="padding-top:150px;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">     
               
            <div class="modal-body" style="padding:40px 50px;"> 
                <h1>Resultados de la busqueda</h1>   
              <ul class="w3-ul w3-hoverable w3-white">               
                {% for i in "x"|rjust:"5" %}
                <li class="w3-padding-16">
                  <img src="{% static 'home/img/img5.jpg' %}" alt="Image" class="w3-left w3-margin-right" style="width:50px">
                  <span class="w3-large">Username</span><br>
                </li>
              {% endfor %}
              </ul>
            </div>
        </div>    
    </div>
  </div>


{% endblock %}

forum/templates/forum/noticiasbuscadas.html
{% extends "forum/escuela.html" %}

{% block content %}
{% load staticfiles %}

<!-- Modal content-->
<div class="modal-dialog">
<div class="modal-content">     
               
        <div class="modal-body" style="padding:40px 50px;"> 
            <h1>Resultados de la busqueda</h1>   
          <ul class="w3-ul w3-hoverable w3-white">               
            {% for i in noticias %}
            <li class="w3-padding-16">
                <a href="/foro/ver/{{i.0}}">
                    <img src={{i.4}} alt="Image" class="w3-left w3-margin-right" style="height:30px; width: 30px">
                </a>
              <span class="w3-large">{{i.1}}</span><br>
            </li>
          {% endfor %}
          </ul>
        </div>
    </div>
</div>

    {% endblock %}