EICO/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^inicio/', include('home.urls', namespace="home")),
    url(r'^foro/', include('forum.urls', namespace="forum")),
    url(r'^calendario/', include('eicocalendar.urls', namespace="calendario")),
    url(r'^perfil/', include('personal.urls', namespace="perfil")),
]

personal/urls.py
from django.conf.urls import url, include
from . import views

app_name = "perfil"
urlpatterns = [ 
                url(r'^$', views.viewProfile, name='viewProfile'),
                url(r'ajeno/(?P<id>[0-9]+)$', views.viewProfileUser, name='viewProfileUser'),
                url(r'editarPerfil/$', views.editarPerfil, name='editarPerfil'),
                url(r'agregarExpecienciaOTrabajo/$', views.agregarExperienciaOTrabajo, name='agregarExperienciaOTrabajo'),
                url(r'agregarEducacion/$', views.agregarEducacion, name='agregarEducacion'),
                url(r'^editar/editarEducacion/(?P<id>[0-9]+)$', views.editarEducacion, name='editarEducacion'),
                url(r'^editar/editarEducacionAux/(?P<id>[0-9]+)$', views.editarEducacionAux, name='editarEducacionAux'),
                url(r'^eliminar/eliminarEducacion/(?P<id>[0-9]+)$', views.eliminarEducacion, name='eliminarEducacion'),
                url(r'^eliminar/eliminareducacionAux/(?P<id>[0-9]+)$', views.eliminarEducacionAux, name='eliminarEducacionAux'),
                url(r'^editar/editarExperiencia/(?P<id>[0-9]+)$', views.editarExperiencia, name='editarExperiencia'),
                url(r'^editar/editarExperienciaAux/(?P<id>[0-9]+)$', views.editarExperienciaAux, name='editarExperienciaAux'),
                url(r'^eliminar/eliminarExperiencia/(?P<id>[0-9]+)$', views.eliminarExperiencia, name='eliminarExperiencia'),
                url(r'^eliminar/eliminarexperienciaAux/(?P<id>[0-9]+)$', views.eliminarExperienciaAux, name='eliminarExperienciaAux'),

                

            ]

personal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

personal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.db import connection
#from django.urls import reverse
from django.core.urlresolvers import reverse

import cloudinary.uploader

cloudinary.config(
    cloud_name = 'poppycloud',
    api_key = '328358331617938',
    api_secret = 'z-7k70XpvP1dl1ZdiqVF0olXp7A'
)


# Create your views here.
def viewProfile(request):


    template = loader.get_template('personal/perfil.html')

    print("hola")
    print(request.session['Usuario'])

    id_usuario = request.session['Usuario']

    print(id_usuario)


    cur = connection.cursor()
    cur.callproc('obtener_usuario_id', [id_usuario,])
    datos_usuario = cur.fetchall()

    print(datos_usuario)

    cur.nextset()
    cur.callproc('obtener_publicaciones_usuario', [id_usuario, ])
    publicaciones_usuario = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_experiencias_o_proyectos_usuario', [id_usuario])
    experiencia = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_educacion_usuario', [id_usuario])
    educacion = cur.fetchall()
    
    
    cur.close

    datos_usuario_detalle = datos_usuario[0]

    print(datos_usuario_detalle)

    context = {
        'datos_usuario': datos_usuario_detalle,
        'publicaciones_usuario': publicaciones_usuario,
        'educacion': educacion,
        'experiencia': experiencia
    }

    return HttpResponse(template.render(context, request))



# Create your views here.
def viewProfileUser(request, id):

    template = None
    print("holaaaaaa")
    if int(id) == int(request.session['Usuario']):
        template = loader.get_template('personal/perfil.html')
    else:
        template = loader.get_template('personal/perfilajeno.html')

    
    cur = connection.cursor()
    cur.callproc('obtener_usuario_id', [id,])
    datos_usuario = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_publicaciones_usuario', [id, ])
    publicaciones_usuario = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_experiencias_o_proyectos_usuario', [id])
    experiencia = cur.fetchall()

    cur.nextset()
    cur.callproc('obtener_educacion_usuario', [id])
    educacion = cur.fetchall()
    
    
    cur.close

    datos_usuario_detalle = datos_usuario[0]

    context = {
        'datos_usuario': datos_usuario_detalle,
        'publicaciones_usuario': publicaciones_usuario,
        'educacion': educacion,
        'experiencia': experiencia
    }

    return HttpResponse(template.render(context, request))



def editarPerfil(request):

    template = loader.get_template('personal/perfil.html')

    id_usuario = request.session['Usuario']

    nombre = request.POST.get('nombre')
    titulo = request.POST.get('titulo')
    puesto_actual = request.POST.get('puesto_actual')
    lugar_trabajo = request.POST.get('lugar_trabajo')
    correo_electronico = request.POST.get('correo_electronico')
    archivo = request.FILES.get("archivo")
    password = request.POST.get("password")

    imagen_subida = cloudinary.uploader.upload(archivo)

    # obtiene la referencia que va a permitir mostrar la imagen en la aplicación
    imagen_subida_url = imagen_subida["secure_url"]

    cur = connection.cursor()
    cur.callproc('editar_usuario', [id_usuario, nombre, correo_electronico, titulo, puesto_actual, lugar_trabajo, imagen_subida_url, password])
    cur.close

    return HttpResponseRedirect(reverse('perfil:viewProfile'))



def agregarExperienciaOTrabajo(request):
    template = loader.get_template('personal/perfil.html')
    id_usuario = request.session['Usuario']

    id_usuario = request.session['Usuario']

    puesto = request.POST.get('puestoexperiencia')
    trabajo = request.POST.get('trabajoexperiencia')
    fecha_inicio = request.POST.get('finicioexperiencia')
    fecha_final = request.POST.get('ffinalexperiencia')
    descripcion = request.POST.get('descripcionexperiencia')

    cur = connection.cursor()
    cur.callproc('insertar_experiencia_o_proyecto', [puesto, trabajo, fecha_inicio, fecha_final, descripcion, id_usuario])
    cur.close
    
    return HttpResponseRedirect(reverse('perfil:viewProfile'))

def agregarEducacion(request):
    template = loader.get_template('personal/perfil.html')

    id_usuario = request.session['Usuario']

    titulo = request.POST.get('tituloeducacion')
    centro_educativo = request.POST.get('centroeducativoeducacion')
    fecha_inicio = request.POST.get('finicioeducacion')
    fecha_final = request.POST.get('ffinaleducacion')
    descripcion = request.POST.get('descripcioneducacion')

    print(titulo)

    cur = connection.cursor()
    cur.callproc('insertar_educacion', [titulo, centro_educativo, fecha_inicio, fecha_final, descripcion, id_usuario])
    cur.close
    
    return HttpResponseRedirect(reverse('perfil:viewProfile'))



def editarEducacion(request, id):
    template = loader.get_template('personal/editareducacion.html')
    context = {
        'id': id
    }
    return HttpResponse(template.render(context, request))


def editarEducacionAux(request, id):
    template = loader.get_template('personal/editareducacion.html')
    
    id_usuario = request.session['Usuario']
    titulo = request.POST.get('tituloeducacion')
    centro_educativo = request.POST.get('centroeducativoeducacion')
    fecha_inicio = request.POST.get('finicioeducacion')
    fecha_final = request.POST.get('ffinaleducacion')
    descripcion = request.POST.get('descripcioneducacion')

    

    cur = connection.cursor()
    cur.callproc('editar_educacion', [id, titulo, centro_educativo, fecha_inicio, fecha_final, descripcion, id_usuario])
    cur.close
    return HttpResponseRedirect(reverse('perfil:viewProfile'))



def editarExperiencia(request, id):
    template = loader.get_template('personal/editarexperiencia.html')
    context = {
        'id': id
    }
    return HttpResponse(template.render(context, request))


def editarExperienciaAux(request, id):
    template = loader.get_template('personal/editarexperiencia.html')
    
    id_usuario = request.session['Usuario']

    puesto = request.POST.get('puestoexperiencia')
    trabajo = request.POST.get('trabajoexperiencia')
    fecha_inicio = request.POST.get('finicioexperiencia')
    fecha_final = request.POST.get('ffinalexperiencia')
    descripcion = request.POST.get('descripcionexperiencia')


    cur = connection.cursor()
    cur.callproc('editar_experiencia_o_proyecto', [id, puesto, trabajo, fecha_inicio, fecha_final, descripcion, id_usuario])
    cur.close
    return HttpResponseRedirect(reverse('perfil:viewProfile'))


def eliminarEducacion(request, id):
    template = loader.get_template('personal/eliminareducacion.html')
    
    context = {
        'id': id
    }
    
    return HttpResponse(template.render(context, request))
    
def eliminarEducacionAux(request, id):
    template = loader.get_template('personal/eliminareducacion.html')
    context = {}
    print("hola")
    cur = connection.cursor()
    cur.callproc('eliminar_educacion', [id])
    cur.close

    return HttpResponseRedirect(reverse('perfil:viewProfile'))




def eliminarExperiencia(request, id):

    template = loader.get_template('personal/eliminarexperiencia.html')
    
    context = {
        'id': id
    }
    
    return HttpResponse(template.render(context, request))
    
    

def eliminarExperienciaAux(request, id):
    template = loader.get_template('personal/eliminarexperiencia.html')
    context = {}
    print("hola")
    cur = connection.cursor()
    cur.callproc('eliminar_experiencia', [id])
    cur.close

    return HttpResponseRedirect(reverse('perfil:viewProfile'))

personal/templates/personal/editareducacion.html
            <div class="modal-content">           
                <div class="modal-body" style="padding:40px 50px;">                
                        <form class="form-signin" method='POST' action='{% url 'perfil:editarEducacionAux' id %}'  > {% csrf_token %}
                            <h1 align="center">Editar Educacion</h1>
                            <br>
                            <input type="text" id="input" name="tituloeducacion" class="form-control" placeholder="Nombre del titulo..." required autofocus>
                            <br>
                            <input type="text" id="input" name="centroeducativoeducacion" class="form-control" placeholder="Centro educativo..." required autofocus>
                            <h5>Inicio</h5>
                            <input type="date" name="finicioeducacion" required>
                            <br>
                            <h5>Finalizacion</h5>
                            <input type="date" name="ffinaleducacion" required>
                            <br>
                            <br>
                            <div class="form-group">
                                    <textarea class="form-control" style="resize: none;" rows="5" id="comment" name="descripcioneducacion" placeholder="Descripcion..."></textarea>
                            </div>
                            <br>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button>
                      </form>      
                </div>
            </div>    
       

personal/templates/personal/editarexperiencia.html
            <!-- Modal content-->
            <div class="modal-content">           
                <div class="modal-body" style="padding:40px 50px;">                
                        <form class="form-signin" method='POST' action='{% url 'perfil:editarExperienciaAux' id %}'  > {% csrf_token %}
                            <h1 align="center">Editar Experiencia</h1>
                            <br>
                            <input type="text" id="input" name="puestoexperiencia" class="form-control" placeholder="Nombre del puesto/Nombre proyecto..." required autofocus>
                            <br>
                            <input type="text" id="input" name="trabajoexperiencia" class="form-control" placeholder="Lugar de trabajo...">
                            <h5>Inicio</h5>
                            <input type="date" name="finicioexperiencia" required>
                            <br>
                            <h5>Finalizacion</h5>
                            <input type="date" name="ffinalexperiencia" required>
                            <br>
                            <br>
                            <div class="form-group">
                                    <textarea class="form-control" name="descripcionexperiencia" style="resize: none;" rows="5" id="comment" placeholder="Descripcion..."></textarea>
                            </div>
                            <br>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Editar</button>
                      </form>      
                </div>
            </div>    
       
            

personal/templates/personal/eliminareducacion.html
<div class="modal-content">
            
                
    <!-- Modal body -->
    <div class="modal-body">
        <h1 align="center">Educación</h1><br>
        <h4>Esta seguro que quiere eliminar la educación</h4>
    </div>
    
    <!-- Modal footer -->
    <div class="modal-footer">
            <a type="submit" href="/perfil/eliminar/eliminareducacionAux/{{id}}">
            
                <button type="submit"  class="btn btn-danger">Eliminar <span></span></button>    
            
            </a>    
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    </div>
    
</div>

personal/templates/personal/eliminarexperiencia.html
<div class="modal-content">
            
                
    <!-- Modal body -->
    <div class="modal-body">
        <h1 align="center">Experiencia</h1><br>
        <h4>Esta seguro que quiere eliminar la experiencia</h4>
    </div>
    
    <!-- Modal footer -->
    <div class="modal-footer">
            <a type="submit" href="/perfil/eliminar/eliminarexperienciaAux/{{id}}">
            
                <button type="submit"  class="btn btn-danger">Eliminar <span></span></button>    
            
            </a>    
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
    </div>
    
</div>

personal/templates/personal/perfilajeno.html
{% extends "home/header.html" %}

{% block content %}
{% load staticfiles %}



<div class="container" style="margin-top:100px;">
        <div class="row">
      
                  <div class="card hovercard">
                      <div class="cardheader">
                            <div align="right">
                                
                             </div>
                      </div>
                      
                      <div class="avatar">
                          <img src={{ datos_usuario.5 }}  class="img-circle" >
                      </div>

                       
                      <div class="info">
                          <div class="title">
                              {{ datos_usuario.0 }}
                          </div>
                          <div class="desc">{{ datos_usuario.2 }}</div>
                          <div class="desc">{{ datos_usuario.3 }}</div>
                          <div class="desc">{{ datos_usuario.4 }}</div>
                          <div class="desc">{{ datos_usuario.1 }}</div>
                      </div>
                  </div>

        </div>


        <!-- Experiencia Proyectos -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                        <div class="col-md-8">
                            <h3><b>Experiencia/Proyectos</b></h3>
                        </div>
                        <div class="col-md-4" align="right">
                            
                        </div>
                </div>

            </div>

            <div class="panel-body">
                <ul class="list-group">
                    <div id="list" style="height: auto; max-height: 200px; overflow-x: hidden;">

                    {% for i in experiencia %}
                    <li class="list-group-item" style="border: none">
                        <div class="media">
                            <div class="media-left">
                                <a href=#>
                                    <span class="glyphicon glyphicon-briefcase" style="font-size: 50px; margin-right:10px;" aria-hidden="true"></span>
                                </a>
                            </div>
                            <div class="media-body">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h4 class="media-heading">Puesto de trabajo / Nombre Proyecto <small><i>{{ i.3|date:"d-m-Y" }}</i></small></h4>
                                    </div>
                                    <div class="col-md-4" align="right">
                                            
                                    </div>
                                </div>
                                <p>
                                    {{i.1}}
                                </p>
                            </div>
                        </div>
                        <br>
                    </li>
                    {% endfor %}
            </div>
        </div>
      
    </div>

    <!-- Educacion -->
    <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                        <div class="col-md-8">
                            <h3><b>Educacion</b></h3>
                        </div>
                        <div class="col-md-4" align="right">
                            
                        </div>
                </div>
                
            </div>

            <div class="panel-body">
                <ul class="list-group">
                    <div id="list" style="height: auto; max-height: 200px; overflow-x: hidden;">

                    {% for i in educacion %}
                    <li class="list-group-item" style="border: none">
                        <div class="media">
                            <div class="media-left">
                                <a href=#>
                                    <span class="glyphicon glyphicon-education" style="font-size: 50px; margin-right:10px;" aria-hidden="true"></span>
                                </a>
                            </div>
                            <div class="media-body">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h4 class="media-heading">Escuela - Titulo <small><i>{{ i.3|date:"d-m-Y" }}</i></small></h4>
                                    </div>
                                    <div class="col-md-4" align="right">
                                            
                                    </div>
                                </div>
                                <p>
                                    {{i.1}}
                                </p>
                            </div>
                        </div>
                        <br>
                    </li>
                    {% endfor %}
            </div>
        </div>
      
    </div>

    <!-- Publicacion -->
    <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                        <div class="col-md-8">
                            <h3><b>Publicaciones</b></h3>
                        </div>
                        <div class="col-md-4" align="right">
                            
                        </div>
                </div>
                
            </div>

            <div class="panel-body">
                <ul class="list-group">
                    <div id="list" style="height: auto; max-height: 200px; overflow-x: hidden;">

                    {% for i in publicaciones_usuario %}
                    <li class="list-group-item" style="border: none">
                        <div class="media">
                            <div class="media-left">
                                <a href="/foro/ver/{{i.5}}">
                                    <span class="glyphicon glyphicon-copy" style="font-size: 50px; margin-right:10px;" aria-hidden="true"></span>
                                 </a>
                            </div>
                            <div class="media-body">
                                <div class="row">
                                    <div class="col-md-8">
                                        <h4 class="media-heading">{{ i.0 }} <small><i>{{ i.3|date:"d-m-Y" }}</i></small></h4>
                                    </div>
                                    <div class="col-md-4" align="right">
                                        
                                    </div>
                                </div>
                                <p>
                                    {{ i.1 }}
                                </p>
                            </div>
                        </div>
                        <br>
                    </li>
                    {% endfor %}
            </div>
        </div>
      
    </div>
    

</div>





{% endblock %}